### ISSUE TITLE
make distcheck fails

### ISSUE THREAD

**Issue by sgeto** [libcheck/check#120]
I guess that there are a few essential files not added as dist targets. It just happened and I have to take care of something else right now, so I don't really have time to find and list the files now. I'll do that ASAP and get back to you.

**Comment by sgeto** [comment]
Better late then never they say.

This is the error message:
```
Making dvi in doc
make[2]: Entering directory '/data/data/com.termux/files/home/check/check-0.11.0/_build/sub/doc'
TEXINPUTS="../../../doc:$TEXINPUTS" \
MAKEINFO='makeinfo   -I ../../../doc' \
texi2dvi  --build-dir=check.t2d -o check.dvi  \
../../../doc/check.texi
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.  If you want to use
this script, you'll need to install TeX (if you don't have it) or change
your PATH or TEX environment variable (if you do).  See the --help
output for more details.                                                                                                                For information about obtaining TeX, please see http://tug.org/texlive,
or do a web search for TeX and your operating system or distro.     make[2]: *** [Makefile:465: check.dvi] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/check/check-0.11.0/_build/sub/doc'
make[1]: *** [Makefile:561: dvi-recursive] Error 1                  make[1]: Leaving directory '/data/data/com.termux/files/home/check/check-0.11.0/_build/sub'                                             make: *** [Makefile:778: distcheck] Error 1
```

Seems like distcheck is unable to find texi2dvi even when it's install. Should I attach my config.log as well?

**Comment by brarcher** [comment]
Do you know if tex is installed on your system? Is it in the PATH?
```
$ which tex
/Library/TeX/texbin/tex
```

I am wondering if the program cannot be found, which may be the reason for the failure?

**Comment by sgeto** [comment]
No I don't. But that didn't bother "make all"
Why would it matter with "make distcheck"?

**Comment by brarcher** [comment]
I think that ```distcheck``` does more than ```all``` (which does not sound intuitive on its face). ```all``` will build the code (official definition [here](https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html#Standard-Targets)). ```distcheck``` ensures that the source can be built and passes tests, can be installed into another directory, can be uninstalled, and can be tarballed up to ensure the distribution can be self contained (documentation [here](https://www.gnu.org/software/automake/manual/html_node/Checking-the-Distribution.html)).

**Comment by sgeto** [comment]
I see. So a distcheck fail doesn't necessarily mean the resulting tarball won't work properly. No need to worry, right?

**Comment by brarcher** [comment]
That is my understanding. To add further, every pull request runs through the prereleasecheck target ([here](https://check.ci.cloudbees.com/job/check-prereleasecheck-github/)), which also attempts distcheck. If that fails the pull request is rejected. To my knowledge if one has TeX installed and in the PATH then distcheck should be successful.

**Comment by brarcher** [comment]
If you believe otherwise, let me know and re-open the issue.
