### ISSUE TITLE
Check for Visual Studio 2010 - without stdbool.h

### ISSUE THREAD

**Issue by bel2125** [libcheck/check#125]
Currently check does not work for Visual Studio 2010 project, because it misses the `stdbool.h` header from the C99 standard. This include was introduced about a year ago in https://github.com/libcheck/check/commit/6c19a8e3feb7b5d305905efefbe2be424a6adde3

Could we just replace this `bool` by an `int`, so older but still common Visual Studio compilers (2010 and even 2012) could use also recent versions of check?

I could prepare a PR if you like.

**Comment by brarcher** [comment]
Hm, sorry that the change broke you on VS 2010. My expectation with using [AppVeyor](https://github.com/libcheck/check/blob/master/appveyor.yml) would be to catch issues like this; maybe the version of VS there is different than 2010.

The function is internal, so there is no problem if the signature is changed. Alternatively, a compile time check could be made for ```stdbool.h``` and if it does not exist provide a ```#define``` for ```true``` and ```false``` in [libcompat.h](https://github.com/libcheck/check/blob/master/lib/libcompat.h) if it does not exist. That would have the benefit of prevent this breakage in the future if someone introduces usage of true/false but is unaware of the unavailability of ```stdbool.h``` in VC 2010.

Either way, I would be glad to accept a pull request with changes.

**Comment by brarcher** [comment]
I see in your project you also added an AppVeyor builds for VC 2010. If you would like to add a build for that in Check's [AppVeyor configuration](https://github.com/libcheck/check/blob/master/appveyor.yml) as well, feel free.

**Comment by bel2125** [comment]
I removed the stdbool dependency (https://github.com/civetweb/check/commit/9c594550554ad05e95a20eb8a3b35c5c3a235b88) and added an AppVeyor configuration (https://github.com/civetweb/check/commit/5eed08f804f76df1a39df707040b684107ca4ba3).

But it turns out, the unit tests of check have several non C89 compliant functions, mainly because variables are not declared "on top" (https://github.com/civetweb/check/commit/5c7b77158570aa1b1851bd1b67a18973cdb6bcde), regex are missing (https://github.com/civetweb/check/commit/2447c87b39c2533992937703734f7fe7418821f9), `INFINITY` and `NAN` are not defined (https://github.com/civetweb/check/commit/2b406f107b94eabebf92d20bb189d2c223e5d51c), and `isnan`/`isinf`/`isfinite` is also missing (https://github.com/civetweb/check/commit/af96d7f55b107f42ce06c30203262f44b4957728). Probably some things could be done in a different way in particular with the infinity / NaN support.

It seems I cannot do a direct unit test of check on AppVeyor (AppVeyor interface does not allow me to add this project), but the indirect test through the CivetWeb build seems to work.

**Comment by bel2125** [comment]
The unit tests are working now for Visual Studio 2010 and 2012.

Please have a look at the PR https://github.com/libcheck/check/pull/129

I encountered some open topics regarding INFINITY / NAN, where you have to decide how you want to have this solved.

I also tried to get Visual Studio 2005, 2008 and 2017 running, but they are no longer / not yet installed in the AppVeyor build image. Maybe it would be the best to remove these three builds from the appveyor file again, and deal with it in a separate PR, if required.

**Comment by brarcher** [comment]
> It seems I cannot do a direct unit test of check on AppVeyor

Is it that I need to add something on Check's AppVeyor interface? If so, what needs to be added?

**Comment by bel2125** [comment]
>>    It seems I cannot do a direct unit test of check on AppVeyor

> Is it that I need to add something on Check's AppVeyor interface? If so, what needs to be added?

I'm not sure if you can config that all forks are also built with AppVeyor.

It's probably somewhat my fault, that I forked check as civetweb/check ("the version of check required for civetweb") instead of bel2125/check ("the version modified by me"), so it is connected with the civetweb organisation github account, while my AppVeyor account is connected to the bel2125 github account. There is an internal link in github making bel2125/civetweb the same as civetweb/civetweb, but there is no such link for check ... I'm not really sure and I don't know if I can solve this without the help of the AppVeyor and/or github support team.
For the moment, I don't you can't do anything.

**Comment by bel2125** [comment]
Solved with PR #129 

In case someone needs Visual Studio 2008 support, the [`appveyor.yml`](https://github.com/libcheck/check/blob/77e445d3b6e5e87bae8d2c46f595a705f96cfbfb/appveyor.yml#L28) file is prepared, the build works, but it seems [some unit tests fail for VS2008](https://ci.appveyor.com/project/brarcher46583/check/build/1.0.531/job/9i530uhw8rtcp3v2#L2330). Fixing the code VS2008 is out of scope for this issue.

Visual Studio 2010, 2012, 2013, 2015 and 2017 build are working now.
