### ISSUE TITLE
Make CK_MAX_MSG_SIZE dynamically configurable?

### ISSUE THREAD

**Issue by orenbenkiki** [libcheck/check#127]
I realize that placing a limit on the message size is a good thing (4GB, shudder...). However, making it a compile-time `#define` seems overly restrictive. How about making it dynamically configurable (keeping 8K as the default limit)?

I just run into a case where I dump two objects to textual format and compare the dumps. The dumps were 2056 characters long... which caused libcheck to die horribly. If the maximal size was configurable I could just bump it up to, say, 16K instead of 8K and solve my problem (my computer has 16GB, surely 16K in a message isn't an issue...?).

I link with the libcheck version I got from apt-get. To modify the limit I'd have to switch to a private patched version - and force my users to do the same. To obey the limit, I'd have to write convoluted code that somehow splits the dumped data on <2K chunks (say, on a line boundary...).

A possible objection is that people might abuse such a dynamic size configuration. True... but if someone _explicitly_ sets the maximal size to 4GB, they can't really complain about the unpleasant side effects - especially if the documentation explained that excessive message sizes are inadvisable.

**Comment by brarcher** [comment]
I've no objection to allowing this to be configurable, perhaps via environment variable. The messages are stored in a file until the test completes, in which case they are read back out. So, only one message should be in memory at a time anyway.

If you would like to prototype making the max size configurable, I would accept the resulting pull request if you are satisfied with the result.
