### ISSUE TITLE
Licensing and attribution for CMake scripts

### ISSUE THREAD

**Issue by Liam-Ryan** [libcheck/check#131]
Hi I've taken your cmake scripts from doc/example/cmake and incorporated into one of my projects.
I'm also looking at updating my C library seed to use these scripts in order to have check testing set up out of the box which will follow a similar format. 

I'm wondering if it's sufficient to include your copying.txt from this folder in the same folder under my project. Also does use of this prevent my use of the MIT license? 

My project is at https://github.com/Liam-Ryan/lrsinglelinkedlist, could you let me know if any changes or additional files are required? I don't intend to distribute check with my project, just the setup to run tests. 

Thanks!

**Comment by brarcher** [comment]
Hm, I've not put thought into the licensing of the build scripts before...

The FindCheck.cmake file appears to be licensed under a BSD license. I think that is compatible with MIT (in terms of what it provides). However, I do not think that you should change the license from BSD to MIT (or if technically you can). Keeping the copying file should be fine.

Are there any other files that you would like to ask about besides FindCheck.cmake?

**Comment by Liam-Ryan** [comment]
Ah thanks I was trying to figure out which license it was and missed those taglines in Findcheck.cmake. I also copied in the vast bulk of the CMakeLists.txt in the directory above it. I'll switch my projects to BSD license and thanks for taking the time to come back to me on this.

**Comment by Liam-Ryan** [comment]
Sorry for the additional noise, I've updated to BSD but I just realised there's no attribution in the CMakeLists.txt at https://github.com/libcheck/check/blob/master/doc/example/CMakeLists.txt which I've only modified slightly and included in the root of my project. Is there anything you'd like me to add to the file? 

My project is only a small toy one but I want to ensure I give credit and license correctly. Thanks again.

**Comment by brarcher** [comment]
I think that if a file does not have a license on it, it takes the license from the project, which is LGPL. However, I wrote the file and do not mind if it is BSD licensed. The following pull request will change the license on that file to BSD: https://github.com/libcheck/check/pull/132. Feel free to use it as a basis for your project, as that is the point of the example. (:

**Comment by Liam-Ryan** [comment]
Thanks very much :)
