### ISSUE TITLE
No ck_assert_double_xxx in check.h

### ISSUE THREAD

**Issue by StephenChips** [libcheck/check#139]
I installed check via `apt-get install check`.

Everything was fine till I used `ck_assert_double_eq` macro in my testing code, then the compiler complained that it cannot link `ck_assert_double_eq`(it supposed it is a function). I glance through the check.h, there are no functions to test double and float value as the API listed.

**Comment by StephenChips** [comment]
The version on apt-get is out-of-date(0.10.0-3), please upload the newest version as soon as possible.

Thanks.

**Comment by brarcher** [comment]
Check 0.10.0 was released on Dec 23, 2015, and the API you are interested in is in Check 0.11.0 released on Dec 17, 2016. If you are interested in the Linux distribution you are using in updating the version of Check which is provided, you will need to contact them directly. I do not have any control over what version of Check downstream distros provide.

In the interim, you are welcome to manually make and install the version of Check you would like to use on your system. That will allow you to use whichever version you would like.

Sorry I cannot be more help.
