### ISSUE TITLE
libinput-test-suite-runner : Failed to create udev rules directory (No such file or directory)

### ISSUE THREAD

**Issue by kyrios123** [libcheck/check#140]
I would like to enable checks while building the libinput package, but I can't manage to get this test working. Could you advise please ?
```
--- command ---
/home/build/YPKG/root/libinput/build/libinput-1.9.1/test/symbols-leak-test.in /home/build/YPKG/root/libinput/build/libinput-1.9.1
-------

4/4 libinput-test-suite-runner              FAIL     0.01 s

--- command ---
/home/build/YPKG/root/libinput/build/libinput-1.9.1/solusBuildDir/libinput-test-suite-runner
--- stderr ---
FAILED: aborting
Failed to create udev rules directory (No such file or directory)
in litest_init_udev_rules() (../test/litest.c:1082)
-------
```

**Comment by brarcher** [comment]
I may need more context into what you are trying and what failures you are hitting.
- Are you able to create a simple hello world test, to show that the build setup is correct?
- Can you provide a link to your proposed tests, and where you are hitting an issue?
- What behavior in libinput are the tests attempting to verify; are the tests attempting to modify the state of the host, or is the system being mocked at some level?

**Comment by kyrios123** [comment]
Sorry was a stupid mistake from me... I was running it with fakeroot and there was some permissions issues.
