### ISSUE TITLE
Arch Linux installation info

### ISSUE THREAD

**Issue by ExcaliburZero** [libcheck/check#15]
Currently the installation page of the website includes installation instructions for Debian and Fedora based Linux distributions, however it would also be useful to include installation instructions for Arch Linux based distros.

Arch Linux provides a Check package that can be installed. It can be installed by running the following command in the terminal:

```
sudo pacman -S check
```

**Comment by brarcher** [comment]
Would you be interested in updating the install page to include information on Arch Linux then submitting a pull request with the change?

https://github.com/libcheck/check/blob/master/web/install.html

**Comment by ExcaliburZero** [comment]
Since #16 has been merged, this issue can now be closed.
