### ISSUE TITLE
Ubuntu apt packages out of date

### ISSUE THREAD

**Issue by BrennenSprimont** [libcheck/check#177]
I'm sure this isn't the right spot for this, but the mailing list link took me to a source forge form and I'm assuming this is no longer maintained.

The latest apt package released on ubuntu is a rather old release: `10.0-3build2` (https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=check&searchon=names)

I'm happy to give compiling from source a go, but I figured yall should know.

**Comment by brarcher** [comment]
Thanks for letting me know. I've seen in the past that distros are slow in updating this package. There may be little incentive to do so, as older versions are probably "good enough". I do not control when downstream distros update their versions, and encourage you to reach out to Ubuntu to see if they are interested in updating. Aside from that, building from source may be your best bet.
