### ISSUE TITLE
Missing header <unistd.h> from file check.c

### ISSUE THREAD

**Issue by mikkoi** [libcheck/check#186]
```
[ 17%] Building C object src/CMakeFiles/check.dir/check.c.o
/Users/[******]/check/src/check.c:393:9: warning: implicitly declaring library function '_exit' with type
      'void (int) __attribute__((noreturn))' [-Wimplicit-function-declaration]
        _exit(1);
        ^
/Users/[******]/check/src/check.c:393:9: note: include the header <unistd.h> or explicitly provide a declaration for '_exit'
/Users/[******]/check/src/check.c:604:16: warning: result of comparison of constant 4294967295 with expression of type
      'clockid_t' is always false [-Wtautological-constant-out-of-range-compare]
    if(clockid == -1)
       ~~~~~~~ ^  ~~
2 warnings generated.
```

**Comment by mikkoi** [comment]
Since header <unistd.h> is not portable (is part of POSIX standard), it needs to be added in a portable way, maybe the same way it is used...

```
#if defined(HAVE_FORK) && HAVE_FORK==1
        _exit(1);
#endif /* HAVE_FORK */
```

**Comment by brarcher** [comment]
Interesting. What platform are you seeing this on? I'm guessing from the paths that it is on macOS. When I try compiling master on my macOS machine I do not see that warning.

check.c includes libcompat.h, and that has the following:
```
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
```
I would expect that unistd.h would be included if configure found it. I wonder why configure did not find it on your system.

**Comment by mikkoi** [comment]
It happens on MacOS. I have not run ./configure at all, just using the CMake build. (`autoreconf --install` fails on MacOS as well, but that's another story.)

**Comment by mikkoi** [comment]
This raises the bigger question, do we want to support both CMake build and autoconf (GNU) build?

**Comment by mikkoi** [comment]
What I meant with my question, was "Does check continue to support both GNU and CMake build, or in the future only CMake build?"
I created another build request for an advanced CMake build which uses the CMake 3 new export system.

**Comment by mikkoi** [comment]
I have fixed this in https://github.com/libcheck/check/pull/202/commits/f00f50374e2366f632e6042c7ee8ed36c59cdf08
