### ISSUE TITLE
something is garbling the output in the log files

### ISSUE THREAD

**Issue by howaboutsynergy** [libcheck/check#188]
**EDIT:** [jump](https://github.com/libcheck/check/issues/188#issuecomment-492782675) to reproduction steps using `check_money` example!

Note: ignore all other comments(of mine) until that one, to save your time :)

-----

testing latest git master local/check 0.12.0.r36.gd6c1ffe-1

```
$ cat do_cd_command.log 
Running suite /src/filemanager
do_c100%: Checks: 4, Failures: 0, Errors: 0
ome:0: Passed
do_cd_command.c:147:P:Core:test_empty_mean_home:1: Passed
do_cd_command.c:147:P:Core:test_empty_mean_home:2: Passed
do_cd_command.c:147:P:Core:test_empty_mean_home:3: Passed
Results for all suites run:
100%: Checks: 4, Failures: 0, Errors: 0
PASS do_cd_command (exit status: 0)
```

or

```
$ cat compare_directories.log 
Running suite /src/filemanager
comp33%: Checks: 6, Failures: 4, Errors: 0
compare_directories.c:183:F:Core:test2:0: Assertion 'right_panel->marked == (int) 1' failed: right_panel->marked == 0, (int) 1 == 1
compare_directories.c:202:F:Core:test3:0: Assertion 'left_panel->marked == (int) 1' failed: left_panel->marked == 0, (int) 1 == 1
compare_directories.c:291:F:Core:loopytest:1: FAILed for _i=1 as follows:
left  panel:somefile.txt size:0 mtime:1557859191
right panel:somefile.txt size:0 mtime:1557859190
result  : left: unmarked, right: unmarked
expected: left: unmarked, right: unmarked
------

compare_directories.c:291:F:Core:loopytest:2: FAILed for _i=2 as follows:
left  panel:somefile.txt size:1 mtime:1557859190
right panel:somefile.txt size:0 mtime:1557859190
result  : left:   marked, right:   marked
expected: left: unmarked, right: unmarked
------

  marked
expected: left: unmarked, right: unmarked
------

Results for all suites run:
33%: Checks: 6, Failures: 4, Errors: 0
FAIL compare_directories (exit status: 1)
```

so this part is from just a few lines before, repeated:
```
  marked
expected: left: unmarked, right: unmarked
------
```

or,

```
$ cat examine_cd.log 
Running suite /src/filemanager
exam100%: Checks: 1, Failures: 0, Errors: 0
assed
Results for all suites run:
100%: Checks: 1, Failures: 0, Errors: 0
PASS examine_cd (exit status: 0)
```

**Comment by brarcher** [comment]
Are you saying that this behavior exists in both Check master and v0.12? Are the logs being reported to stdout, and are there multiple threads in the test that are outputting to stdout besides libcheck? If the output is changed to be a file by adding the following environment variable [[link](https://libcheck.github.io/check/doc/check_html/check_4.html#Test-Logging)]:
```
CK_LOG_FILE_NAME=log.txt
```
is the issue still present?

**Comment by howaboutsynergy** [comment]
> Are you saying that this behavior exists in both Check master and v0.12?

yes



> Are the logs being reported to stdout

I think they are created by `check`*, but not shown on stdout, I just `cat` them afterwards
\* ie. `srunner_set_log (sr, "do_cd_command.log");`


> are there multiple threads in the test that are outputting to stdout besides libcheck?

unsure, should I `export CK_FORK=no` ? is that enough to ensure 1 thread(s) ?
Did it, but hit the same issue.


> If the output is changed to be a file by adding the following environment variable [[link](https://libcheck.github.io/check/doc/check_html/check_4.html#Test-Logging)]:

I did `export CK_LOG_FILE_NAME=log.txt` but the issue persists and I can't find any `log.txt` file via `$ find ../../../../ -name log.txt`
Looks like those `srunner_set_log (sr, "do_cd_command.log");` take precedence also as per mentioned:
> If log file is specified with both CK_LOG_FILE_NAME and srunner_set_log(), the name provided to srunner_set_log() will be used.

timestamp of log seems to be up to date with the time that I run `make check`:
```
$ cat do_cd_command.log
Running suite /src/filemanager
do_c100%: Checks: 4, Failures: 0, Errors: 0
ome:0: Passed
do_cd_command.c:147:P:Core:test_empty_mean_home:1: Passed
do_cd_command.c:147:P:Core:test_empty_mean_home:2: Passed
do_cd_command.c:147:P:Core:test_empty_mean_home:3: Passed
Results for all suites run:
100%: Checks: 4, Failures: 0, Errors: 0
PASS do_cd_command (exit status: 0)
```
(this is the (unchanged) test from [`mc`](https://github.com/MidnightCommander/mc/blob/master/tests/src/filemanager/do_cd_command.c#L172) )

**Comment by howaboutsynergy** [comment]
I just realized something:
the log line from test 1 is overwritten with the penultimate line's contents: `100%: Checks: 4, Failures: 0, Errors: 0` in this:

```
$ cat compare_directories.log 
Running suite /src/filemanager
comp100%: Checks: 4, Failures: 0, Errors: 0
ssed
compare_directories.c:186:P:Core:test2:0: Passed
compare_directories.c:206:P:Core:test3:0: Passed
compare_directories.c:374:P:Core:allinone:0: Passed
Results for all suites run:
100%: Checks: 4, Failures: 0, Errors: 0
PASS compare_directories (exit status: 0)
```

what it should look like (guessed):
```
$ cat compare_directories.log 
Running suite /src/filemanager
compare_directories.c:166:P:Core:test1:0: Passed
compare_directories.c:186:P:Core:test2:0: Passed
compare_directories.c:206:P:Core:test3:0: Passed
compare_directories.c:374:P:Core:allinone:0: Passed
Results for all suites run:
100%: Checks: 4, Failures: 0, Errors: 0
PASS compare_directories (exit status: 0)
```
I just replaced the first occurent of `100%: Checks: 4, Failures: 0, Errors: 0`(40 chars with newline) with the missing 40 chars(guessed): `are_directories.c:166:P:Core:test1:0: Pa`.

**Comment by howaboutsynergy** [comment]
> If the output is changed to be a file by adding the following environment variable [[link](https://libcheck.github.io/check/doc/check_html/check_4.html#Test-Logging)]:
> 
> ```
> CK_LOG_FILE_NAME=log.txt
> ```
> 
> is the issue still present?

I did the opposite and the issue goes away.
I made output be stdout by replacing `srunner_set_log (sr, "do_cd_command.log");` with `srunner_set_log (sr, "-");` and the output isn't on stdout, it's still inside that log file, but it's not messed up:
```
$ cat do_cd_command.log 
Running suite(s): /src/filemanager
Running suite /src/filemanager
do_cd_command.c:147:P:Core:test_empty_mean_home:0: Passed
do_cd_command.c:147:P:Core:test_empty_mean_home:1: Passed
do_cd_command.c:147:P:Core:test_empty_mean_home:2: Passed
do_cd_command.c:147:P:Core:test_empty_mean_home:3: Passed
100%: Checks: 4, Failures: 0, Errors: 0
Results for all suites run:
100%: Checks: 4, Failures: 0, Errors: 0
PASS do_cd_command (exit status: 0)
```

**Comment by howaboutsynergy** [comment]
I just tested `check_money` and they don't have a `srunner_set_log` and the `.log` file `check_money.log` is generated. Thus if I add `srunner_set_log (sr, "check_money.log");` myself in `check_money.c` I obviously hit this garbling issue.

```
$ grep . *.log
check_money.log:Running suite Money
check_money.log:chec100%: Checks: 3, Failures: 0, Errors: 0
check_money.log: Passed
check_money.log:check_money.c:52:P:Limits:test_money_create_neg:0: Passed
check_money.log:check_money.c:56:P:Limits:test_money_create_zero:0: Passed
check_money.log:Results for all suites run:
check_money.log:100%: Checks: 3, Failures: 0, Errors: 0
check_money.log:PASS check_money (exit status: 0)
```

Ergo, the issue is... two writers racing to write to the same log file!! one is implied by the Makefile.am or whatever(unsure what exactly lol), and the other is because I put an explicit `srunner_set_log (sr, "check_money.log");` line !
So workaround is to put `srunner_set_log (sr, "-");` stdout line! 
Or even better, don't put any such line! :D 

So, I'm not sure if I should close this or a warning(or doc change) would be nice somewhere ?

**Comment by howaboutsynergy** [comment]
oh I found the other writer, apparently:
filename: `/test-driver`:

```
...
# Test script is run here.
"$@" >$log_file 2>&1 
...
# Report the test outcome and exit status in the logs, so that one can
# know whether the test passed or failed simply by looking at the '.log'
# file, without the need of also peaking into the corresponding '.trs'
# file (automake bug#11814).
echo "$res $test_name (exit status: $estatus)" >>$log_file           
...
```

**Comment by howaboutsynergy** [comment]
Ok here's reproduction steps:

1. `mkdir /tmp/1`
2. `cp -a /usr/share/doc/check/example/ /tmp/1/`
3. `cd /tmp/1/example/`
4. `ls -la`
```
drwxr-xr-x 4 user user 4096 15.05.2019 18:37 ./
drwxr-xr-x 3 user user 4096 15.05.2019 20:47 ../
drwxr-xr-x 2 user user 4096 15.05.2019 18:37 src/
drwxr-xr-x 2 user user 4096 15.05.2019 18:37 tests/
-rw-r--r-- 1 user user  868 15.05.2019 18:37 configure.ac
-rw-r--r-- 1 user user   80 15.05.2019 18:37 Makefile.am
-rw-r--r-- 1 user user 2206 15.05.2019 18:37 README
```
5. `autoreconf --install`
6. `./configure`
7. `make`
8. `cd tests`
9. `make check`
so far all good, no issues here!
10. apply the following patch with `patch -Np1 -i /tmp/file.patch` (assuming you saved it as `/tmp/file.patch`):
```diff
diff --git a/tests/Makefile b/tests/Makefile
index 3dd32e7..67bcf7a 100644
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -796,7 +796,8 @@ recheck: all $(check_PROGRAMS)
 	        TEST_LOGS="$$log_list"; \
 	exit $$?
 check_money.log: check_money$(EXEEXT)
-	@p='check_money$(EXEEXT)'; \
+	set -vx; \
+	p='check_money$(EXEEXT)'; \
 	b='check_money'; \
 	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
 	--log-file $$b.log --trs-file $$b.trs \
diff --git a/tests/check_money.c b/tests/check_money.c
index b5a3004..ab3ed0e 100644
--- a/tests/check_money.c
+++ b/tests/check_money.c
@@ -98,6 +98,11 @@ int main(void)
     s = money_suite();
     sr = srunner_create(s);
 
+#if 1 //set to 1 for bad output, as per: https://github.com/libcheck/check/issues/188
+    srunner_set_log (sr, "check_money.log");
+#else // no problem:
+    srunner_set_log (sr, "-");
+#endif
     srunner_run_all(sr, CK_NORMAL);
     number_failed = srunner_ntests_failed(sr);
     srunner_free(sr);
```
11. `rm check_money.log; make check && { echo '------'; cat check_money.log; }`
notice how the output is bad/garbled here! hence, this issue.
12. change the `#if 1` line inside `check_money.c` to `#if 0` to see how the good output would look like.

Output when `#if 0` (aka good) [not everything shown below]:
```
...
/bin/sh:3+ /bin/sh ../test-driver --test-name check_money --log-file check_money.log --trs-file check_money.trs --color-tests yes --enable-hard-errors yes --expect-failure no -- ./check_money
...
Running suite(s): Money
Running suite Money
check_money.c:42:P:Core:test_money_create:0: Passed
check_money.c:52:P:Limits:test_money_create_neg:0: Passed
check_money.c:56:P:Limits:test_money_create_zero:0: Passed
100%: Checks: 3, Failures: 0, Errors: 0
Results for all suites run:
100%: Checks: 3, Failures: 0, Errors: 0
PASS check_money (exit status: 0)
```

Output when `#if 1` (aka bad) [not everything shown below]:
```
...
/bin/sh:3+ /bin/sh ../test-driver --test-name check_money --log-file check_money.log --trs-file check_money.trs --color-tests yes --enable-hard-errors yes --expect-failure no -- ./check_money
...
------
Running suite Money
chec100%: Checks: 3, Failures: 0, Errors: 0
 Passed
check_money.c:52:P:Limits:test_money_create_neg:0: Passed
check_money.c:56:P:Limits:test_money_create_zero:0: Passed
Results for all suites run:
100%: Checks: 3, Failures: 0, Errors: 0
PASS check_money (exit status: 0)
```

**Comment by howaboutsynergy** [comment]
non-`check` reproduction steps:
```c
#include <stdio.h>
  
int main() {
  FILE *f=NULL;
  f = fopen("/tmp/a_out_.log", "w");
  if (NULL == f) {
    fprintf(stderr,"oopsie\n");
  } else {
    fprintf(stdout, "Something");
    fprintf(f," messy ");
    fprintf(f," jessy\n");
    fprintf(stdout, " or another\n");
    fprintf(f,"More stuff\n");
    fclose(f);                                                                                                                  
  }
}
```

```
$ gcc a.c && { ./a.out >/tmp/a_out_.log ; cat /tmp/a_out_.log ; }
Something or another
uff
```

So, I guess it's not a bug in `check` right?

**Comment by howaboutsynergy** [comment]
Hey there is a workaround, thanks to `<twkm>` and `<Learath2>` on channel `##C` on freenode IRC, looks like `check` could see that `stdout` and the log file are both on the same device and same inode, and if so, then use only `stdout` for outputting.
Check can be done in `src/check_log.c` in `static FILE *srunner_open_file(const char *filename)` function. I'll try to do that, for fun.

**Comment by brarcher** [comment]
If I'm following along correctly, it seems that autotools is generating a Makefile which is directing stdout to a log file, and the test itself is configured to write to the same log file.

I've not seen that before, maybe it is a newer feature of autotools. I do not think that it warrants having a workaround in libcheck; if one's build system is logging the test output and that is not desirable it should be disabled in the build system rather than compensating in the application. If you figure out how to disable the logging from autotools and you choose to go that route drop a note here, in case someone else runs into the same issue.

I'll close this issue, as there is nothing to do from libcheck. If you disagree, let me know.

**Comment by howaboutsynergy** [comment]
While I will be using [that patch](https://github.com/libcheck/check/issues/188#issuecomment-492852881) myself(though limited to Linux(or POSIX?) systems), there is another way to workaround this issue that you might be interested in, thanks to an [answer](https://stackoverflow.com/a/56168216/11509478) by John Bollinger, and that is: to make a change in both `test-driver` and in `check`, such that, when either is opening the log file, they do create it if it does not exist, and if it does exist then they should just open it in append mode.

In other words:
for `test-driver`:
```patch
--- /tmp/test-driver	2018-09-18 15:06:54.000000000 +0200
+++ /usr/share/automake-1.16/test-driver	2019-05-16 17:58:09.690988983 +0200
@@ -104,7 +104,8 @@ trap "st=141; $do_exit" 13
 trap "st=143; $do_exit" 15
 
 # Test script is run here.
-"$@" >$log_file 2>&1
+echo -n "" >"$log_file"
+"$@" >>"$log_file" 2>&1
 estatus=$?
 
 if test $enable_hard_errors = no && test $estatus -eq 99; then
```

and for `check` in file `src/check_log.c`:
```patch
diff --git a/src/check_log.c b/src/check_log.c
index c785b33..0051f35 100644
--- a/src/check_log.c
+++ b/src/check_log.c
     }
     else
     {
-        f = fopen(filename, "w");
+        f = fopen(filename, "a");
+        if(f == NULL)
+        {
+            f = fopen(filename, "w");
+        }
         if(f == NULL)
         {
             eprintf("Error in call to fopen while opening file %s:", __FILE__,
```

This workaround however, won't protect against any other caller redirecting the stdout to a file in write mode(ie. `check_money >/tmp/my.log`) as opposed to append mode(ie. `check_money >>/tmp/my.log`) as the first workaround would. It's my main reason why I want to use the [first](https://github.com/libcheck/check/issues/188#issuecomment-492852881) one. The second reason would be that it doesn't require any change in the caller(s) (ie. `check_money >/tmp/my.log` is a-okay).

I've tested the above patches to work with the check_money [repro. steps](https://github.com/libcheck/check/issues/188#issuecomment-492782675), so output is correct:
```
Running suite(s): Money
Running suite Money
check_money.c:42:P:Core:test_money_create:0: Passed
check_money.c:52:P:Limits:test_money_create_neg:0: Passed
check_money.c:56:P:Limits:test_money_create_zero:0: Passed
100%: Checks: 3, Failures: 0, Errors: 0
Results for all suites run:
100%: Checks: 3, Failures: 0, Errors: 0
PASS check_money (exit status: 0)
```

**Comment by howaboutsynergy** [comment]
ah, I made a mistake for `check_log.c` using `"a"` I assumed it opens it in append mode ONLY if it exists! but `man 3 fopen` says: 
> `a`  Open for appending (writing at end of file).  **The file is created if it does not exist.**  The stream  is  positioned at the end of the file.

So, feel free to fix that so that it does the same thing that `test-driver` does: create file if it doesn't exist, then open in append mode.

**Comment by howaboutsynergy** [comment]
So, in conclusion, I would argue that, in general(ie. any program), opening logs as well as redirection, should **both** be done with `O_APPEND | O_TRUNC | O_WRONLY | O_CREAT`, and in case `fopen()` is wanted instead of `open()` then always use it like:
```c
FILE *f=NULL;
int fd = open(filename, O_APPEND | O_WRONLY | O_CREAT | O_TRUNC);
if(fd != -1) {
  f = fdopen(fd, "a");
}
if(f == NULL)
{
//failed
} else { //succeeded 
}
//... eventually
fclose(f); // close(fd) not needed
```

However, while that may seem to work(so far), I hear that some form or locking would be required, assuming that concurrent `write(2)`(aka `man 2 write`) are not running synchronously! If they do run synchronously, system-wide (or at least, per file), then nothing more would be needed, no locks! The above way to open log&redirection would be enough, as long as both are open this way. Only one is [not](https://stackoverflow.com/a/56168216/11509478) enough!

If you ask me, it seems that the latter is the case(ergo, hooray!):
> For  a seekable file (i.e., one to which lseek(2) may be applied, for example, a regular file) writing takes place at the file offset, and the file offset is incremented by the number  of  bytes  actually  written.   If  the  file  was open(2)ed  with  O_APPEND, the file offset is first set to the end of the file before writing.  The adjustment of the file offset and the write operation are performed as an atomic step.

So, thoughts?

**Comment by howaboutsynergy** [comment]
Great news: I was using `open()` with `O_CREAT` wrongly (above, and in any other places thus far) by not supplying the `mode` argument! and thus random mode flags would be [set](https://gist.github.com/howaboutsynergy/4dc0c41d6244d91a7dfd07159b905fe9#gistcomment-2920146) on the file!!!!!!!! It amazes me that you can get away with this with like no errors (or warnings; not even shellcheck) :D

from `man 2 open`:
> The mode argument specifies the file mode bits be applied when a new file is created.  This argument  must  be supplied  when O_CREAT or O_TMPFILE is specified in flags; if neither O_CREAT nor O_TMPFILE is specified, then mode is ignored.  The effective mode is modified by the process's umask in the usual way: in the absence of  a default  ACL, the mode of the created file is (mode & ~umask).  Note that this mode applies only to future accesses of the newly created file; the open() call that creates a read-only file may well return  a  read/write file descriptor.

```c
  /* Open FILE with access OFLAG.  If O_CREAT or O_TMPFILE is in OFLAG,
     a third argument is the file protection.  */
  int
  __libc_open (const char *file, int oflag)
  {
--  int mode;
  
    if (file == NULL)
      {
>>      __set_errno (EINVAL);
        return -1;
      }
  
    if (__OPEN_NEEDS_MODE (oflag))                                                                                              
      {
        va_list arg;
>>      va_start(arg, oflag);
        mode = va_arg(arg, int);
        va_end(arg);
      }
  
>>  __set_errno (ENOSYS);
    return -1;
  }
```

**Comment by howaboutsynergy** [comment]
ok I got it then: https://github.com/libcheck/check/issues/187#issuecomment-493541548

**Comment by brarcher** [comment]
Let me try to catch up. 

I'm not sure I agree with the need for making test logging append. Conceptually a Check unit testing program is an independent run through various tests, and keeping the results independent from other results seems reasonable. Appending to an existing log may actually be a surprise rather than a feature. In the situation you ran into two streams were being written to the same file, correct? That seems invalid, and the separate streams should be configured to write to different files.

**Comment by howaboutsynergy** [comment]
> I'm not sure I agree with the need for making test logging append.
> Appending to an existing log may actually be a surprise rather than a feature.

Ah, it's not just append, it's `O_APPEND | O_TRUNC`(with `| O_WRONLY | O_CREAT`) which is like first re-creating the file(so it's 0 bytes initially due to O_TRUNC) and then appending to it(which is supposedly: `Opening a file in append mode (a as the first character of mode) causes  all  subsequent  write  operations  to  this stream to occur at end-of-file, as if preceded the call: fseek(stream, 0, SEEK_END);` from `man 3 fopen`, or from `man 3p open`: `O_APPEND      If set, the file offset shall be set to the end of the file prior to each write.`, or from `man 2 open`: `O_APPEND The  file  is  opened  in  append mode.  Before each write(2), the file offset is positioned at the end of the file, as if with lseek(2).  The modification of the file offset and the write operation  are  performed  as  a single atomic step.` - although see [1] to find how true that is with `fopen` at least)

`automake` could also do that in their `test-driver` script, I suggested it [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=35762)

> In the situation you ran into two streams were being written to the same file, correct? 

Yes.
Midnight Commander is(and has been) using this in their tests(bug [here](https://midnight-commander.org/ticket/3986)), for example in
https://github.com/MidnightCommander/mc/blob/ee08fa9f56929b5ed2f7404b64c6e3654a1a1848/tests/src/filemanager/do_cd_command.c#L172 
but I guess either they didn't know it's the same log file that `/usr/share/automake-1.16/test-driver` was logging to, or likely they know but just wanted to log to the same file so as to avoid having more than 1 log file for each test.


But it turns out there are other situations, a bit unrelated to this(although this could still hit them), where multiple streams in append mode can still interleave their output [1] especially if buffer size is less than 128 bytes.

[1] https://sourceware.org/bugzilla/show_bug.cgi?id=24621 

Anyway, I'm quite happy with my workarounds. Applied locally in all of these Arch Linux packages: `bash`, `automake`, `check`.

I don't expect `check` to make any changes because of all this. But this was a really fun experience in discovering all this stuff. Thank you btw!

**Comment by brarcher** [comment]
Thanks for sharing your experience
