### ISSUE TITLE
missing <unistd.h> in some files

### ISSUE THREAD

**Issue by DexterMagnific** [libcheck/check#196]
Hi,

<unistd.h> is missing in the following files

-  src/check_msg.c
-  tests/check_check_fork.c
-  tests/check_check_master.c

Regards

**Comment by mikkoi** [comment]
I have fixed this in https://github.com/libcheck/check/pull/202/commits/f00f50374e2366f632e6042c7ee8ed36c59cdf08

**Comment by mikkoi** [comment]
Solved in https://github.com/libcheck/check/pull/209/commits/f63378cd2e2e9330860406305f8e8f2bccf489f9
Merged to master.

**Comment by jflopezfernandez** [comment]
@brarcher Can this issue be closed?

**Comment by brarcher** [comment]
Yep, thanks
