### ISSUE TITLE
Fixtures without global vars

### ISSUE THREAD

**Issue by DexterMagnific** [libcheck/check#197]
Hi,

Is there a way for fixtures to return some context object which will be later passed to the unit tests ?

In the check doc, the context is stored as a global var.
Thanks

**Comment by brarcher** [comment]
There is no direct support for this in Check. You will need to capture the state you are interested in and make it accessible to tests some other way. For example, you could create a setter function for fixtures to save state and a getter function for unit tests call to retrieve an instance of this state.

Note though that what gets saved may depend on if fork() is being used in the unit tests. For example, if unit tests can modify the state, then test behavior might change if fork() is enabled vs disabled.

**Comment by DexterMagnific** [comment]
Thanks, did not take into account the fork() case. Passing a context can only be useful in non fork mode, where each of the unit tests performs a step of a whole long test.
