### ISSUE TITLE
CMake Error: export Unknown arguments.

### ISSUE THREAD

**Issue by dmcbeing** [libcheck/check#207]
I am unable to build check on CentOS 7.6.

I have cloned the latest revision (at the time) 2d77d16ff2f038b99c36e658ec0ea1ddea79b9ed.
During the configuration stage of CMake i get the following error:

```
CMake Error at CMakeLists.txt:393 (export):
   export Unknown arguments.
```
I am certain that the issue is caused due to the older CMake version (2.8.12.2) installed by Centos.
Although 2.8.12.2 is technically bigger than the cmake_minimum_required(2.8).
I assume that the `export` function as used in Check's CMakeList.txt has not yet been added in 2.8.12.2.

To work around this error, i commented the offending export statement:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2c822ea..1781d3e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -390,10 +390,10 @@ write_basic_package_version_file(
     COMPATIBILITY AnyNewerVersion
 )
 
-export(EXPORT check-targets
-    FILE "${CMAKE_CURRENT_BINARY_DIR}/check-targets.cmake"
-    NAMESPACE Check::
-)
+#export(EXPORT check-targets
+#    FILE "${CMAKE_CURRENT_BINARY_DIR}/check-targets.cmake"
+#    NAMESPACE Check::
+#)
 
 install(EXPORT check-targets
     NAMESPACE Check::
```
This allows me to build the library, but the resulting check-targets.cmake might not be correct.

Two things can be done:

- [ ] ** make Check buildable with 2.8.12.2 or the specified 2.8 **
- [ ] ** increase the cmake_minimum_required() to the actual minimun required value, so no-one else gets this error.**

Thanks for your time and the Check project.

**Comment by mikkoi** [comment]
I am fixing this currently. CMake minimum will be raised to 3.9.

**Comment by mikkoi** [comment]
Solved in commit https://github.com/libcheck/check/pull/209/commits/24901a43e9804674693ee532c704b8182901410f
Merged to master.

**Comment by dmcbeing** [comment]
Thanks again, closing issue.
