### ISSUE TITLE
Sun Studio build requires C99

### ISSUE THREAD

**Issue by despair86** [libcheck/check#216]
CMake on this platform selects Sun Studio by default (which is the opposite of the old GNU Build System configure), but the use of `__VA_ARGS__` is not supported as an extension even with `CFLAGS='-std=gnu89 -features=extensions'`. Changing the `CMAKE_C_STANDARD` to C99 fixes this.

**Comment by mikkoi** [comment]
Which platform are you on? Solaris?

CMake defaults on different compilers, often deciding after first `cc` in `PATH`. This can be overridden easily by setting the variable `CC` on the command line. https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Useful-Variables#compilers-and-tools
E.g. `CC=clang cmake -D CMAKE_BUILD_TYPE=Debug -D CHECK_ENABLE_TESTS=True ../check`

**Comment by despair86** [comment]
I was just following the instructions on the website, but using cmake instead of the GNU Build system

**Comment by mikkoi** [comment]
CMake build is currently only supported on Windows. On Unix side, please use GNU Autotools. CMake for Unix and Linux builds is still in beta.

**Comment by despair86** [comment]
I mean, *it worked*, but good to know. thanks!

**Comment by despair86** [comment]
all of the other projects I'm working on have migrated exclusively to CMake

**Comment by mikkoi** [comment]
Check is heading towards the same goal. CMake is better supported on Windows. The Windows build is already quite stable but when we "merge" the Unix compatible CMake build into it, a lot of beta testing is necessary. Thanks for helping.
