### ISSUE TITLE
Test for custom assert() function

### ISSUE THREAD

**Issue by smavridis** [libcheck/check#223]
Hi, this is more of a question than an issue.

As part of a framework i am developing, i have created an assert function, that (on failure) dumps a stack trace on screen before calling abort().

```
void _my_assert(int value,const char * expr,const char * file,int line)
{
	if(!value)
		return;
	void * bt[128];
	char ** bt_syms;
	int bt_size = 128;
	int bt_indx;
	bt_size = backtrace(bt, bt_size);
	bt_syms = backtrace_symbols(bt, bt_size);
	for(bt_indx = 1 ; bt_indx < bt_size ; bt_indx++)
	{
		fprintf(stderr,"%s\n",bt_syms[bt_indx]);
	}
	fprintf(stderr,"my_assert(%s) @ %s:%d\n",expr,file+FILE_PREFIX_LEN,line);
	abort();
}
```
To test it i have added the following test to my existing unit tests:

```
START_TEST(test_assert)
{
	my_assert(0);
	ck_abort_msg("Should've aborted...");
}
END_TEST
```
From reading the documentation, i understood that `tcase_add_test_raise_signal` would capture the abort() signal, so this is what i added in suite_init():

``tcase_add_test_raise_signal(tc_single,test_assert,6);	// SIGABRT``

However running the test with cmake, i get the following error:

```
11/11 Test #11: my_assert ........................Child aborted***Exception:   4.74 sec

91% tests passed, 1 tests failed out of 11

Total Test time (real) =   9.52 sec

The following tests FAILED:
         11 - my_assert (Child aborted)
```

I tried with checked and unchecked fixtures, but it did not seem to work with either.
What am i missing?

ps:Thank you for creating check, it has been a time saver at many times.

**Comment by brarcher** [comment]
Hm. I'd expect that what you are trying would work. There are tests in Check that verify similar behavior, such as:

https://github.com/libcheck/check/blob/285d04b3d461ba68dc39e0f9e847784fb6064bb3/tests/check_check_sub.c#L3226

Check does not use abort internally to signal anything, so I do not think there is a bug related to that. In your example you are assuming that SIGABRT is 6. For Linux, this should be the case: [signal.h](https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/signal.h#L16). Are you using Linux? Is there still an issue if you replace '6' with SIGABRT from signal.h? That is the only thing that comes to mind right now.

**Comment by smavridis** [comment]
Thanks for the feedback, it made me look my code again...
I am in Linux so 6 is the correct signal.
What i had wrong was i was running with CK_NOFORK and that was the issue.

Thanks again
