### ISSUE TITLE
FindCheck.cmake is not consistent with check.pc

### ISSUE THREAD

**Issue by dernasherbrezon** [libcheck/check#236]
FindCheck.cmake has only "check" library:

https://github.com/libcheck/check/blob/c5d9592923fde0f2deb61de24793719e5894af64/doc/example/cmake/FindCheck.cmake#L36

While check.pc can have "m", "rt", "pthread":

https://github.com/libcheck/check/blob/c5d9592923fde0f2deb61de24793719e5894af64/CMakeLists.txt#L420

Actually seeing 2 issues here:

1. Linking with the static libcheck is failing. See #156  I guess "m" and "pthread" libraries are actually mandatory.
2. Two places where lib dependencies defined for cmake. Is it possible to drop handcrafted search from FindCheck.cmake and rely only on pkg-config results? Or remove pkg-config from dependencies and rely purely on CMake's find_package?

**Comment by mikkoi** [comment]
Are you using the newest check version 0.13.0?
If so, you do not need FindCheck.cmake at all. Commit https://github.com/libcheck/check/commit/56c347df2d69b6a56ce9a56b7f0b1984a1ffd4b7 contains instructions. They are missing from the example project at the moment.

In general, when working with CMake projects (using one from another) it is better to not use pkg-config. Pkg-config is mostly used when operating with GNU Autotools, or plain makefiles.

**Comment by dernasherbrezon** [comment]
Got it.

I tried to re-build [my project](https://github.com/dernasherbrezon/apt-transport-swift) in Ubuntu 18.04. This is LTE Ubuntu and they have only check version 0.10.x

**Comment by mikkoi** [comment]
Can you download from repo and build yourself?
Just build in your homedir and do not install at all, i.e. just run cmake && make, not make install. CMake will then add the project to the user local package registry: `~/.cmake/packages/check`. Then find_package() will find it even without it having been installed.
