### ISSUE TITLE
Success/Fail/Error output for each test case in a test suite 

### ISSUE THREAD

**Issue by Benardi** [libcheck/check#237]
I have recently used **check** and gone through the existing tutorials I could find.
The most comprehensive output (CK_VERBOSE) I have gathered so far refers to the success of a **test suite**. Something in the following format:
![image](https://user-images.githubusercontent.com/9937551/71643502-67202600-2c99-11ea-8e19-3702d3c11315.png)

Is there some way to gather information about the success of each **test case** ? And, if so is there an existing material/example I might have missed ? 

I've created three **test cases** for one of my **test suites** and executed the **test suite** using the flag CK_VERBOSE. Despite doing so there was no difference in the output, only the success of the **test suite** was mentioned.

**Comment by brarcher** [comment]
I may misunderstanding the question. Just so the nomenclature is the same, Check will run a **Suite Runner**, a Suite Runner can have one or more **Test Suites**, a Test Suite can have one or more **Test Cases**, and a Test Case can have one or more **Tests**. 

The various logging outputs that Check uses all report the result of individual Tests. I do not think that they report the pass/fail of the Test Cases or Test Suites, only the Tests contained within. 

There are some examples of the different logging types and what they provide [here](https://libcheck.github.io/check/doc/check_html/check_4.html#Test-Logging). The code which outputs the results is found in [check_log.c](https://github.com/libcheck/check/blob/master/src/check_log.c), for reference. For example, the stdout logger code is in function [stdout_lfun](https://github.com/libcheck/check/blob/master/src/check_log.c#L179). I do not see any logging of test results after a Test Case or Test Suite completes.

**Comment by Benardi** [comment]
It seems the output that goes to the console, which I believe to be called  print_output in the *check* module is somewhat limited (The picture I sent in my first comment).

Looks like you pointed in the right direction, the logging files you mentioned  have have all the information that I need. They contain the results of the individual **Tests** as you said:

![image](https://user-images.githubusercontent.com/9937551/71648179-ee908800-2cdf-11ea-821b-f4d5e9b5f6aa.png)

Thank you, @brarcher
