### ISSUE TITLE
Automated tests for windows build

### ISSUE THREAD

**Issue by jd-boyd** [libcheck/check#28]
Would it be too much to ask for automated tests for the Windows platform as well?  A lot of projects use the AppVeyor service for that.

For developers who don't use windows, it would help raise assurances that we aren't breaking this project on windows with pull requests being made.

**Comment by brarcher** [comment]
Oh nice, I did not know there was a CI available for Windows!

Looking at the sign-up, it seems easy to add projects on one's personal account. It is not clear yet how to add an organization. There is a [help page](http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations) on the topic, but signing up with a different account still only found my personal project and not libcheck's. I'll have to play with this more to see what I am doing wrong.

**Comment by brarcher** [comment]
Automated tests are now running on AppVeyor for MSVC, Visual Studios, MinGW, MinGW-64, and Cygwin. There is also a build (but not a test) to check that gcc can cross-compile for MinGW on Linux. This is everything that I can think of, and hopefully covers all the necessary bases.

Thanks for the suggestion!
