### ISSUE TITLE
Requesting updates to README.

### ISSUE THREAD

**Issue by jd-boyd** [libcheck/check#32]
It would be nice if the README was updated to a format that github better supports, like markdown, reStructuredText, etc.  A full list of supported formats can be seen here: https://github.com/github/markup/blob/master/README.md

Personally, I think markdown is a pretty reasonable default choice.

Also, it would be nice if the travis and appveyer status icons were added.  THat would be a matter of adding the following lines (if markdown, some adjustment needed for other formats)
```
[![Travis Build Status](https://travis-ci.org/libcheck/check.svg?branch=master)](https://travis-ci.org/libcheck/check)
[![Appveyor Build Status](https://ci.appveyor.com/api/projects/status/github/libcheck/check?svg=true)](https://ci.appveyor.com/project/libcheck/check/branch/master)
```

If there are no objects before I find the time to do this, I will just make a pull request for it.

**Comment by krichter722** [comment]
Content changes should also be included (`INSTALL` no longer exists and there're no build instructions or a file with build instructions mentioned).

I can open a separate issue for that if you prefer.

**Comment by brarcher** [comment]
> It would be nice if the README was updated to a format that github better supports, like markdown, 

If you are interested in updating the README in markdown, that would be great

> INSTALL no longer exists

Oh, I guess the INSTALL file became a [webpage](http://libcheck.github.io/check/web/install.html), but the README was never updated. Perhaps once the README is updated the reference to INSTALL can be replaced with a link to the page.

> it would be nice if the travis and appveyer status icons were added. 

That also sounds good

**Comment by jd-boyd** [comment]
FWIW, I think build directions should go straight in the initial README to lower the amount of effort to get started.  I linked to the install page for the list of pre-packaged install options.  I can of course edit further.

**Comment by brarcher** [comment]
The contents of README.md look good to me.
