### ISSUE TITLE
configure in doc/example fails with "cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."" when autoconf is used

### ISSUE THREAD

**Issue by krichter722** [libcheck/check#34]
`cmake . && make && make test` works fine. `README` suggest that both work fine. Output:

```
$ autoreconf -i -v -f
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:6: installing 'build-aux/compile'
configure.ac:16: installing 'build-aux/missing'
src/Makefile.am: installing 'build-aux/depcomp'
autoreconf: Leaving directory `.'
$ ./configure 
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

experienced with 0.10.0-69-g82cdb29

**Comment by brarcher** [comment]
My guess is that something necessary for the configure script to run is missing. A quick [Google search](https://acassis.wordpress.com/2012/05/13/configure-error-cannot-find-install-sh-install-sh-or-shtool-in/) points out that you may not have libtool, shtool, and/or autogen installed. If this is the Ubuntu system mentioned in another issue, could you try installing these and see if it resolves the problem?
```
sudo apt-get install libtool
sudo apt-get install shtool
sudo apt-get install autogen
```

As a side question, does this occur using Check 0.10.0 with the provided configure script? How about generating one using autoreconf?

**Comment by krichter722** [comment]
Sorry, I'm an idiot for not mentioning that this happens in `doc/example`, but some of your comment still applies.

> My guess is that something necessary for the configure script to run is missing. A quick Google search points out that you may not have libtool, shtool, and/or autogen installed. If this is the Ubuntu system mentioned in another issue, could you try installing these and see if it resolves the problem?

Doesn't help because they were already installed. It's the same system used in #33 (it doesn't seem to like `check` unfortunately).

> As a side question, does this occur using Check 0.10.0 with the provided configure script? How about generating one using autoreconf?

There's no `configure` in `doc/example`.

**Comment by brarcher** [comment]
There is a [Jenkins job](https://check.ci.cloudbees.com/job/check-example-github/34/console) which tests that the example is buildable on each pull request, and that is currently passing. Looking at its output and comparing it to what you observe, I see the following line from the Jenkins job:
```
05:58:21 configure.ac:6: installing `build-aux/ar-lib'
05:58:21 configure.ac:25: installing `build-aux/compile'
05:58:21 configure.ac:20: installing `build-aux/config.guess'
05:58:21 configure.ac:20: installing `build-aux/config.sub'
05:58:21 configure.ac:16: installing `build-aux/install-sh'
05:58:21 configure.ac:16: installing `build-aux/missing'
```
and the following from your output:
```
configure.ac:6: installing 'build-aux/compile'
configure.ac:16: installing 'build-aux/missing'
```
For whatever reason, on the GNU/Linux machine backing the Jenkins node the install-sh script is generated, but on your system it is not.

[This site](https://www.gc3.uzh.ch/blog/Autotools_tutorial/) suggests running the following in order to generate the missing files. Could you give it a try and see what happens?
```
automake --add-missing
```
If that works, then we will need to determine why the missing files were not all generated.

**Comment by brarcher** [comment]
Did not mean to close the issue just yet. Pull request #37 should resolve this issue. Would you mind confirming this?

**Comment by brarcher** [comment]
I've not heard any follow-up on this issue. If this is still occurring and you would like to continue pursuing it, please re-open.
