### ISSUE TITLE
The same TCase* can be added multiple times

### ISSUE THREAD

**Issue by RyDroid** [libcheck/check#50]
Hi.

`suite_add_tcase(s, my_tc); suite_add_tcase(s, my_tc);` works without error or warning. When the suite is freed, it apparently tries to deallocate my_tc 2 times. so "free(): invalid pointer" happens.
I suppose that the test cases are managed in an array without checking that are already in it like a set. It should not be hard to fix : not adding multiple times the same test case and displaying a nice warning or error. Moreover, it would be easier for users to remove a non-obvious bug, generally due to copy-paste.

Regards.

**Comment by brarcher** [comment]
This should now be resolved in master.
