### ISSUE TITLE
undefined reference to srunner_set_tap() 

### ISSUE THREAD

**Issue by r8d8** [libcheck/check#59]
Can't set up logging to use TAP.
Check.c hasn't any implementation.

**Comment by brarcher** [comment]
Can you provide more details on the issue you are seeing? 

- What version of Check are you using, and on what system? 
- What is the configure and make output leading to the compilation failure? 
- Can you provide a minimal example which does not build on your system?

**Comment by r8d8** [comment]
Hi,
Am using Debian 8 Jessie, with Check 0.10.0
check.h in /usr/include - haven't prototype for srunner_set_tap().


Trying to use this function straight forward, as in tutoria:

*int main(void) {*
*    int number_failed;*
*    Suite *s = rbuf_suite();*
*    SRunner *sr = srunner_create(s);*

*    srunner_set_tap(sr, "tests_log.tap");*
*    srunner_run_all(sr, CK_VERBOSE);*
*    number_failed = srunner_ntests_failed(sr);*
*    srunner_free(sr);*

*    return (number_failed == 0) ? EXIT_SUCCESS : EXIT_FAILURE;*
*}*

Log for *configure* and *make check* in attachments.

**Comment by brarcher** [comment]
There is an example of using srunner_set_tap() in Check: [ex_output.c](https://github.com/libcheck/check/blob/master/tests/ex_output.c). That is able to compile and run against Check during each build; it is responsible for running several unit tests. This give some indication that building and using tcase_set_tap() should work.

The following example program is able to build against Check 0.10.0:

```
#include <check.h>
#include <stdlib.h>

START_TEST(test_pass)
{
    ck_assert_msg(1 == 1, "Shouldn't see this");
}
END_TEST

int main(void)
{
	Suite *s;
	TCase *tc;
	SRunner *sr;
	int number_failed;
	
	s = suite_create("S");
	tc = tcase_create("T");
	suite_add_tcase(s, tc);
	tcase_add_test(tc, test_pass);

	sr = srunner_create(s);
	srunner_set_tap(sr, "tests_log.tap");
	srunner_run_all(sr, CK_VERBOSE);
	number_failed = srunner_ntests_failed(sr);

	return number_failed == 0 ? EXIT_SUCCESS : EXIT_FAILURE;
}
```

On OSX this is successfully built using the following:

```
$ clang  example.c -o example `pkg-config check --cflags --libs`
```

The example runs as expected:

```
$ ./example 
Running suite(s): S
100%: Checks: 1, Failures: 0, Errors: 0
example.c:6:P:T:test_pass:0: Passed
$ cat tests_log.tap 
ok 1 - example.c:T:test_pass: Passed
1..1
```

Can you provide a simplified example which is unable to build, so that I reproduce the failure for myself?

**Comment by brarcher** [comment]
I've not heard any follow-up on this issue. If this is still occurring and you would like to continue pursuing it, please re-open.

**Comment by wblangdon** [comment]
This is still a problem. Just downloaded ViennaRNA-2.5.0.tar.gz
./configure --disable-openmp
make (needed to fixup callbacks-sc.i and RNA_wrap.cpp to replace av_top_index by av_len) then
make check fails with this error: ie
make[3]: Entering directory ...ViennaRNA-2.5.0/tests'
  CC       energy_evaluation.o
energy_evaluation.ts: In function ‘main’:
energy_evaluation.ts:214:5: warning: implicit declaration of function ‘srunner_set_tap’; did you mean ‘srunner_set_xml’? [-Wimplicit-function-declaration]
  214 |     srunner_set_tap(sr, "-");
      |     ^~~~~~~~~~~~~~~
      |     srunner_set_xml
  CCLD     energy_evaluation
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: /tmp/energy_evaluation.QqJtsm.ltrans0.ltrans.o: in function `main':
.../ViennaRNA-2.5.0/tests/energy_evaluation.ts:214: undefined reference to `srunner_set_tap'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1022: energy_evaluation] Error 1
make[3]: Leaving directory ...ViennaRNA-2.5.0/tests'

gcc version 10.2.1 20210130 (Red Hat 10.2.1-11) (GCC)
cmake version 3.19.4

**Comment by wblangdon** [comment]
This is still a problem.
Just downloaded ViennaRNA-2.5.1.tar.gz
./configure --enable-sse
make; fails with (4 similar compilation errors)
RNA_wrap.cpp: In function 'int sc_add_f_perl_callback(vrna_fold_compound_t*, SV*)':
RNA_wrap.cpp:6498:16: error: 'av_top_index' was not declared in this scope; did you mean 'make_loop_index'?
 6498 |           if ((av_top_index((AV *)SvRV(callback)) + 1) < (int)vc->n_seq) {
      |                ^~~~~~~~~~~~
      |                make_loop_index

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
gcc version 10.2.1 20210130 (Red Hat 10.2.1-11) (GCC)
