### ISSUE TITLE
Definition of pid_t not found on plain Windows

### ISSUE THREAD

**Issue by kaoh** [libcheck/check#78]
`check.h` defines:

    CK_DLL_EXP pid_t CK_EXPORT check_fork(void);

A fix would be:

```
#ifdef WIN32
#define pid_t int
#endif
```

**Comment by Artox** [comment]
This is still a thing!

**Comment by brarcher** [comment]
Take a look at https://github.com/libcheck/check/issues/78 and see if it is what you are thinking, or if you suggest a different fix.

**Comment by Artox** [comment]
Yes thats exactly what I'd like to see.

**Comment by brarcher** [comment]
This should be resolved in the next release of Check.
