### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by tp-m** [libcheck/check#83]
Hi,

please could you make a new release, or regular releases in general (ie. at least every 6 months)?

The last release is from more than a year ago.

Thanks!

**Comment by brarcher** [comment]
Yep, you are right. It has been too long. I'll get together a release. Thanks for the poke.

**Comment by brarcher** [comment]
A new release has been created, [0.11.0](https://github.com/libcheck/check/releases/tag/0.11.0).

**Comment by tp-m** [comment]
Fantastic, thanks for getting this out so quickly!
